import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Productivity from "./UI/Productivity";



const Nunitosans = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Nunitosans.variable} ${Nunitosans.variable} antialiased`}
      >
        <Header />
        <Productivity />
        {children}
      </body>
    </html>
  );
}
